#!/usr/bin/env node
/**
 * Sync Data Script
 *
 * Copies JSON data files from data/ to public/api/ before build.
 * Auto-detects available years from filenames.
 * Generates src/generated/years.ts so the frontend knows which years exist.
 *
 * Usage:
 *   node scripts/sync-data.js
 *   npm run sync-data
 */

const fs = require('fs');
const path = require('path');

const SOURCE_DIR = path.join(process.cwd(), 'data');
const TARGET_DIR = path.join(process.cwd(), 'public', 'api');
const GENERATED_DIR = path.join(process.cwd(), 'src', 'generated');

/**
 * Auto-detect data files and extract years.
 * Matches f9_launches_YYYY.json and world_launches_YYYY.json (ignores _q1-_q4 intermediates).
 */
function discoverDataFiles() {
  const files = fs.readdirSync(SOURCE_DIR).filter(f => f.endsWith('.json'));
  const yearPattern = /^(f9_launches|world_launches)_(\d{4})\.json$/;
  const years = new Set();
  const dataFiles = [];

  for (const file of files) {
    const match = file.match(yearPattern);
    if (match) {
      dataFiles.push(file);
      years.add(parseInt(match[2], 10));
    }
  }

  return {
    dataFiles: dataFiles.sort(),
    years: [...years].sort(),
  };
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`📁 Created directory: ${dir}`);
  }
}

function syncFile(filename) {
  const sourcePath = path.join(SOURCE_DIR, filename);
  const targetPath = path.join(TARGET_DIR, filename);

  if (!fs.existsSync(sourcePath)) {
    console.log(`⚠️  Skipped: ${filename} (not found in data/)`);
    return false;
  }

  fs.copyFileSync(sourcePath, targetPath);
  const stats = fs.statSync(targetPath);
  const sizeKB = (stats.size / 1024).toFixed(1);
  console.log(`✅ Synced: ${filename} (${sizeKB} KB)`);
  return true;
}

function generateYearsFile(years) {
  ensureDir(GENERATED_DIR);

  const content = `// Auto-generated by scripts/sync-data.js — do not edit manually
export const SUPPORTED_YEARS = [${years.join(', ')}] as const;
export type SupportedYear = (typeof SUPPORTED_YEARS)[number];
`;

  const filePath = path.join(GENERATED_DIR, 'years.ts');
  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`✅ Generated: src/generated/years.ts (years: ${years.join(', ')})`);
}

function main() {
  console.log('\n🔄 Syncing data files to public/api/...\n');
  console.log(`   Source: ${SOURCE_DIR}`);
  console.log(`   Target: ${TARGET_DIR}\n`);

  const { dataFiles, years } = discoverDataFiles();
  console.log(`   Discovered ${dataFiles.length} data files for years: ${years.join(', ')}\n`);

  ensureDir(TARGET_DIR);

  let synced = 0;
  let skipped = 0;

  for (const file of dataFiles) {
    if (syncFile(file)) {
      synced++;
    } else {
      skipped++;
    }
  }

  generateYearsFile(years);

  console.log(`\n📊 Summary: ${synced} synced, ${skipped} skipped, years: [${years.join(', ')}]\n`);
}

main();
